theme         : jekyll-theme-minimal
title         : 
description   : 
logo          : https://media.licdn.com/dms/image/C5603AQFJYlsHsX0rIA/profile-displayphoto-shrink_200_200/0/1641760252833?e=1686182400&v=beta&t=Vr9AvyJIEKKK8d6j0r_J2gkp25dqadMLdtnBR1NZREI
show_downloads: false


url            : https://jnajafi.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
orcid          : "http://orcid.org/yourorcidurl"


author:
  name          : Javad Najafi
  bio           : "Welcome to my page"
